### ISSUE TITLE
Enhancement: Internacionalização

### ISSUE THREAD

**Issue by derekstavis** [pagarme/pilot#342]
## Contexto

Uma library de UI é composta de componentes reusáveis. Com a premissa do reusável não podemos deixar de considerar os textos que compões essa biblioteca.

Muitos dos componentes já recebem seus textos via propriedades, como botões e inputs, porém componentes um pouco mais complexos, compostos de outros componentes, geralmente acabam por adicionar strings que também deveriam permitir ser customizadas, seja por motivos de internacionalização, localização ou vocabulário com o cliente.

## Requisitos

- [x] `DateSelector`
  + Personalizado
  + Dia & Período
  + Hoje
  + Botões Cancelar/Confirmar
  + x dias selecionado
  + Dias da semana/mês (momentjs)
- [x] `Switch`
  + Label de on/off
- [x] `Pagination`
  + Label do "1 de X" páginas

~- [ ] `Filters`~
  ~+ Placholder do Seletor de datas~
  ~+ Placholder do Campo de busca~
  ~+ Mais/Menos/Editar filtros~
  ~+ Título de opções selecionadas~
  ~+ Props do `DateSelector`~
  ~+ Botões de Filtrar/Limpar~

## Proposta de interface

Adicionar propriedades para customização de texto em todos os componentes da UI library. Exemplo:

```
<Pagination strings={{ of: "de" }} />
```

Como os componentes tem em sua natureza programática a nomeação em inglês, acordamos que as propriedades de strings também deverão assim ser, logo todas as strings deverão ser nomeadas em em inglês e ter seus defaults values nesta língua.

A partir do momento em que estes componentes estiverem integrados na master, todos os componentes desenvolvidos desde então devem ser feitos seguindo o mesmo padrão.

## Critérios de aceite

- [x] Deve renderizar sem nenhuma propriede de string
- [x] Deve renderizar com propriedades de string

**Comment by gabrielgodoy** [comment]
Hey @derekstavis, I started working at Stone RJ this week as a web developer. 

I am very interested in collaborating on the Pilot project. I have some experience with React as well.

I already cloned the project to be familiar with its code.

Do you think I can help with some issue or feature? Please let me know!

Thanks!

**Comment by derekstavis** [comment]
Hey, come talk to us on gitter.im/pagarme/pilot @gabrielgodoy!

**Comment by gabrielgodoy** [comment]
@derekstavis @vitorvmiguel 

Hey guys, I took a look at the rules for this issue and had some doubts.

If we use `strings` props as an object for the translations, the user will be forced to pass the entire `strings` object to the component.

Because if the user pass only some properties to the `strings` prop, the entire defaultProps of `strings` inside the component will be overwritten, and some properties of the object `strings` might end up being `undefined`. This happens because defaultProps only does a shallow merge. But what if the user only wants to translate only some parts of the component and keep others default?

1. One viable solution would be to turn "flat" the `strings` props object, so the user can translate only some properties if he wants to. And every prop related to translation can have a prefix "lang" or something.

2. Another solution would be to keep the `strings` props as an object, but not use defaultProps. So before the component renders, we can have some function to do a merge with what was passed from `strings` props, and some default translations object in english:

```
function handleTranslation() {
  const userTranslations = this.props.strings
  return {
    ...someDefaultTranslations, 
    ...userTranslations,
  } 
}
```

3. Or we can even try to use some i18n library, but I do not think that adding one more dependency would be cool.


What do you think?

**Comment by derekstavis** [comment]
>Because if the user pass only some properties to the strings prop, the entire defaultProps of strings inside the component will be overwritten, and some properties of the object strings might end up being undefined if the user forgets to pass some.

You have already gave the answer that was on my mind:

>So before the component renders, we can have some function to do a merge with what was passed from strings props, and some default translations object in english.

About using i18n libraries, although we must use some library in the application itself, I wouldn't like to tie the base components to a translation library. We are already tying this components to a theming library, but as it is very simple and thin, we can export it directly from our component library package, making it easy to replace by our own implementation or by another library.

**Comment by LeoNero** [comment]
Podemos fechar?

**Comment by vitorvmiguel** [comment]
@LeoNero Acho que sim, editei tirando `Filters`. 

@derekstavis podemos fechar?

**Comment by derekstavis** [comment]
Done!
